version: "3.9"

services:
  develop:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY
    image: gnuradio-limesdr:develop
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "$HOME/.Xauthority:/home/gnuradio/.Xauthority:rw"
      # Added to mount the USB FTDI device to the container so we can plug in while running
      - "/dev/bus/usb/:/dev/bus/usb/"
      - "/data:/data"
    network_mode: "host"
    ports:
      - "6000-6063:6000-6063"
    command: 
      - /bin/bash


      